# Generated by Django 3.1.1 on 2021-05-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_auto_20210507_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='values',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='yearOfStudy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='studentNumber',
            field=models.CharField(default=0, max_length=9),
        ),
    ]
