# Generated by Django 3.1.1 on 2021-05-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_auto_20210508_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
