# Generated by Django 3.1.1 on 2021-05-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_auto_20210508_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
