# Generated by Django 3.1.1 on 2021-05-08 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meet', '0007_auto_20210508_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='requestee',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='accounts.account'),
        ),
    ]
