# Generated by Django 3.1.1 on 2021-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0008_auto_20210508_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
