# Generated by Django 3.1.1 on 2021-05-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('meet', '0009_meetup_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='requestee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to='accounts.account'),
        ),
    ]
