# Generated by Django 3.1.1 on 2021-05-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_auto_20210508_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(help_text='Take this opportunity to describe yourself! Feel free to say anything or everything about what defines you as a person.', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(help_text='Write your interest here in this format: interest1 interest2 interest3... You can put as many as you want to.', max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='values',
            field=models.CharField(help_text='Write at least three of the vaues you hold dearly, eg, liberal,Christian. Write in the form value1 value2 value3...', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='yearOfStudy',
            field=models.IntegerField(help_text='What is your current year of study? This helps us match you with people within your age bracket.', null=True),
        ),
    ]
