# Generated by Django 3.1.1 on 2021-05-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_auto_20210508_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetup',
            name='numberOfPeople',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
