# Generated by Django 3.1.1 on 2021-05-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0012_meetup_numberofpeople'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetup',
            name='description',
            field=models.TextField(help_text='Give a description about the type of meetup this would be. Is it an activity (hiking, skiing etc), or just chilling at a public place on campus.', null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='location',
            field=models.CharField(help_text='Where would you want to meet ?If anywhere on campus, just say On Campus.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='numberOfPeople',
            field=models.IntegerField(default=1, help_text='How many people would you like us to notify? Due to covid protocols, we can only allow a maximum of 3 people.', null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='time',
            field=models.CharField(help_text='At around what time of the day would you want to meet?', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='meetup',
            name='title',
            field=models.CharField(help_text="Give your meetup request a title, eg , 'Looking for a group of friends to go hiking with'.Try to keep it short.", max_length=100, null=True),
        ),
    ]
