# Generated by Django 3.1.1 on 2021-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_auto_20210508_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='What is the name of your event', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(help_text='When is your event?', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(help_text='How many people should be at this event', null=True),
        ),
    ]
